### ISSUE TITLE
v2 Release Timeline

### ISSUE THREAD

**Issue by bgribaudo** [liprec/powerbi-hierarchySlicer#100]
Hello,

Do you have a rough idea of when v2 will be released? I'm really looking forward to this new version, as it will make HierarchySlicer a certified visual!

Thanks,
Ben

**Comment by liprec** [comment]
Hi @bgribaudo ,

The v2 version is now available and should be certified in a couple of weeks.

Thanks, Jan Pieter

**Comment by bgribaudo** [comment]
Thank you @liprec! This is wonderful news!
