### ISSUE TITLE
[BUG] Older version is loaded into powerbi

### ISSUE THREAD

**Issue by markbaas** [liprec/powerbi-hierarchySlicer#102]
Not sure how to exactly describe the bug, but the main problem is that I don't see certain features that you implemented in the latest version. I installed the custom visual both from the marketplace and by compiling from source (master) and this is the result:

![image](https://user-images.githubusercontent.com/1153495/66552086-04f7cf00-eb49-11e9-8e9b-b7f035a3addc.png)

Now, when I change the package name in the pbiviz.json, I do get the newest features:

![image](https://user-images.githubusercontent.com/1153495/66552176-2953ab80-eb49-11e9-8624-9511a0dccd76.png)

This gives me the idea that power bi somehow is caching an older version of the visual. I asked a colleague to reproduce and he got the same result as I did. Therefore, I thought it was wisely to share this problem with you. Did you or anyone already experience this?

**Comment by liprec** [comment]
The latest version has been replaced by an older version as there were issues with Internet Explorer.
A new version is being released in a couple of weeks.

**Comment by deesaini** [comment]
Is the latest version of the visual Micro Soft certified?

**Comment by liprec** [comment]
The new v2 version will be certified eventually.

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
