### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by adamlofton** [liprec/powerbi-hierarchySlicer#103]
Hi Jan. We are using and loving the Hierarchy slicer but noticed that our report in Production that is using the slicer now has 2 titles across the top. My guess is one is a Title and one is a Header. Did you recently update the Hierarchy Slicer visual that would make some of the features work differently in the PBI Service?

**To Reproduce**
1. Go to our report in Power BI that uses the Slicer
2. Review that the report is inheriting the name of the attribute and displaying both the attribute name and the custom name created

**Expected behavior**
The name of the attribute is not displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/35043194/67225443-13b37100-f3e8-11e9-83e4-49ed1c594f9b.png)

**Power BI info (please complete the following information):**
 - Online [yes/no]:  Yes
 - Browser [e.g. chrome, safari]: Chrome
 - Desktop version:

**Additional context**
This issue was reported by Russel Brinkerhoff on 10/2/2019 as well, who is also working for my organization and is not able to comment today.  The solution was implemented for that bug by you I believe, on 10/3 I think.

**Comment by adamlofton** [comment]
PS - Version = Version: 2.74.5619.621 64-bit (October 2019)

**Comment by liprec** [comment]
Accidentally a wrong version of the HierarchySlicer has been released by Microsoft which is causing this behavior, but now the correct version is again available.
But when the V2 version will be released in a couple of weeks, the behavior of the title will be different, so please disable it already in your reports to prevent it from showing when the new version will be released.

**Comment by russty72** [comment]
Jan, Thanks so much for your response to my colleague Adam. Because our reports impact so many users I'd like to volunteer to be a Beta Tester of the V2 version. That way I can give you feedback on how the Hierarchy Slicer is performing and we can also be prepared for the impact when that version lands.

Please let me know how I can help support your Beta Testing efforts. 
Kind Regards,
Russ Brinkerhoff
email: russb@slalom.com

**Comment by russty72** [comment]
Hi Jan. Following up on my above comment. Please shoot me an email when you can. Thanks!
