### ISSUE TITLE
[REQ] make it available to use with SSAS multidimensional database

### ISSUE THREAD

**Issue by aisbergde** [liprec/powerbi-hierarchySlicer#104]
I try to use the Hierachy Slicer on a multidimensional SSAS model, but it looks like this is not supported

**Describe the solution you'd like**
I would like to use the hierarchy slicer on multidimensional SSAS databases to slice predefined hierarchies or to define customer hierarchies

**Describe alternatives you've considered**
I am still searching

**Additional context**
![image](https://user-images.githubusercontent.com/9020187/67751624-be9fdc80-fa31-11e9-91cb-5d843cb2ccc2.png)

**Comment by liprec** [comment]
Hi @aisbergde ,

The HierarchySlicer is supporting SSAS Multidimensional models.
Is this still an issue today as a new version is released this week?

-JP

**Comment by aisbergde** [comment]
Today I tested again and now it works.
