### ISSUE TITLE
Hierarchy Slicer not showing in service

### ISSUE THREAD

**Issue by JGPete** [liprec/powerbi-hierarchySlicer#107]
I have a slicer pane with 6 or so hierarchy slicers. Slicer pane is repeated and slicers sync'd on multiple pages. Everything is OK in Pbi desktop, but when published to service the service does not display one of the slicers (others OK). If I unsync the slicer in question then everything appears fine.
This may be something in the November update. Prior to that it was fine.
Help
Pete

**Comment by liprec** [comment]
Hi @JGPete ,

Thanks for your feedback and this should not happen. What you can try is to clear the browser cache to make sure that Power BI is using the latest version. And what browser are you using?

Thanks, Jan Pieter

**Comment by JGPete** [comment]
HI Jan
Was using IE11, but problem seems to have gone away!! at least on another quick login to service.
My pbix is a long way from production!
Probably working now because of a cache clearance as you suggested.
Please assume it's all OK unless I come back and re-log the issue
Thanks
Pete
