### ISSUE TITLE
You cannot select more than 3 years.

### ISSUE THREAD

**Issue by aabensur** [liprec/powerbi-hierarchySlicer#108]
Hello, thanks for the work done Hierarchyslicer seems great to me, but the same thing happens to me as in the example you put on the web, you cannot select more than 3 years, if in the example you want to select 2013, 2014, 2015 and 2016 no You can because it only lets you select 3 years and only happens when used on the web, in PBI DESKTOP it works well, I think it didn't happen before.
PS: sorry for my English, I speak Spanish

**Comment by liprec** [comment]
Hi @aabensur,

Sorry to hear that it is not always working for you. Can you share a file sample with me? You may use mail@datascenarios.nl as email.

Thanks, Jan Pieter

**Comment by russty72** [comment]
I'm seeing something similar but not related to a Date hierarchy. We are noticing that we can select 3 items but once the 4th is selected the slicer de-selects the previous items. The behavior is strange as it only seems to happen at Level 1 of the hierarchy.

**Comment by liprec** [comment]
Hi @russty72 ,

Thanks for the feedback and indeed I can reproduce it with a date hierarchy. I will take a look at what is happening.

-JP

**Comment by tomrenfrodbg** [comment]
I am seeing this same issue, but I can select only two level 1 items.  The third de-selects them all.  I can work around it by selecting all items at level 2 or lower levels of the hierarchy, and it only behaves incorrectly under the PowerBI service.  PowerBI desktop works properly.  This is at version 2.0.22 of the visual.

**Comment by aabensur** [comment]
I sent you an email to mail@datascenarios.nl

thank you!

**Comment by russty72** [comment]
Jan Pieter,
Just to confirm the issue we are seeing is similar to what @tomrenfrodbg shared up above. The issue only happens on level 1. We are limited to only selecting two level 1 items. When selecting the third it de-selects them all. I'll record a video and will email it to you to demonstrate.

**Comment by ktgreen00** [comment]
I am experiencing the same issue.  My data source is a multidimensional cube and using a category hierarchy already in the model.

**Comment by tomrenfrodbg** [comment]
I had previously reported that "it only behaves incorrectly under the PowerBI service. PowerBI desktop works properly. This is at version 2.0.22 of the visual."

As of the February 2020 release of PowerBI Desktop, with version 2.0.22 of the visual, I now get the same behavior in the service and the desktop tool, as described.  If I select two level 1 items, then try to select a 3rd, all are unselected.

Thank you

**Comment by liprec** [comment]
@All: these issues should be fixed, see #116
