### ISSUE TITLE
Type 'undefined' is not assignable to type 'VisualConstructorOptions'.

### ISSUE THREAD

**Issue by HardRock4Life** [liprec/powerbi-hierarchySlicer#110]
I'm getting this error at `powerbi-hierarchySlicer-master\.tmp\precompile\visualPlugin.ts(15,40)`. Who had the same issue, how did you solve it? Thank you!

**Comment by liprec** [comment]
Duplicate of #94

**Comment by liprec** [comment]
Please update to the latest version of the powerbi-visuals-tools, which contain fixes for this issue.

**Comment by dynamicapps** [comment]
Still getting this issue with 3.1.14.  Is it something you're still looking at?
Thx

**Comment by liprec** [comment]
Hi @dynamicapps,

I have just checked it with my current build and with the 3.1.14 tooling it is working for me.
Can you try to run an `npm update` first and then run `npx pbiviz package` to check?

Thanks, JP

**Comment by dynamicapps** [comment]
@liprec Thanks, JP.  I should have posted back, but the issue just went away the next time I went back to it.  Thanks for the response and thank you so much for posting your source.
