### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by russty72** [liprec/powerbi-hierarchySlicer#111]
Selecting the first value on the Hierarchy Slicer will sometimes un-select right after it's clicked. If you wait 1/2 second the issue seems to resolve itself and will re-select.
**To Reproduce**
1. Select a top level value
2. Notice the check box appears then clears
3. Wait for a second or so
4. The check box returns checked

**Expected behavior**
Check box will select and remain selected.

**Screenshots**
I'll email a video to you reproducing the issue.

**Comment by liprec** [comment]
Hi Russ,

There is an issue with slicer selections and my slicer.
I am currently looking into it together with Microsoft to identify what is going wrong.

-JP

**Comment by liprec** [comment]
Hi @russty72,

This issues should be fixed, see #116

-JP
