### ISSUE TITLE
Selection disappearing with sync slicer / publish and 

### ISSUE THREAD

**Issue by liprec** [liprec/powerbi-hierarchySlicer#116]
Hi all,

Currently there is a general issue with my slicer and the selection it is retrieving from Power BI.
Currently I am investigating the issue together with Microsoft to identify what is causing this behavior.

Sorry for the inconvenience.

-JP

**Comment by liprec** [comment]
In the last period several fixes has been released that fixes above issues and the HierarchySlicer should work as exected again.

Sorry for the inconvenience it caused.

-JP

**Comment by liprec** [comment]
If you still experience an issue, please create a new issue so I can track it easier.

Thanks, JP

**Comment by aabensur** [comment]
> Hi all,
> 
> Currently there is a general issue with my slicer and the selection it is retrieving from Power BI.
> Currently I am investigating the issue together with Microsoft to identify what is causing this behavior.
> 
> Sorry for the inconvenience.
> 
> -JP

Excellent!  thanks for the hard work you do!

**Comment by aabensur** [comment]
> In the last period several fixes has been released that fixes above issues and the HierarchySlicer should work as exected again.
> 
> Sorry for the inconvenience it caused.
> 
> -JP

Excellent!  thanks for the hard work you do!
