### ISSUE TITLE
Not working post deployment to Power BI Report Server

### ISSUE THREAD

**Issue by mubin4all** [liprec/powerbi-hierarchySlicer#119]
Hi 
I have used hierarchy slicer and added hierarchy from SSAS OLAP cube, it is working fine in Power BI desktop Report server Jan 2020 edition, but when i uploaded it to Report server hierarchy slicer is not loading in page of the report.

Your reply will be a great help.

Regards
Mubin

**Comment by liprec** [comment]
Can you validate if the latest hotfix version of the Report Server Januari version is installed?
There have been some issues with Power BI and the visual that is causing this behavior.

-JP

**Comment by mubin4all** [comment]
Using latest release of power bi desktop and report server jan2020 release.

Regards
