### ISSUE TITLE
HierarchySlicer v. 1.1.5.0 still have problems

### ISSUE THREAD

**Issue by goldtael** [liprec/powerbi-hierarchySlicer#12]
Hi Jan:
I tested the new version 1.1.5.0 last night at home and it worked good. However, when I try it again today in the office, I still have problems with single select allows multi select, expand and collapse and clear are not functioning. My Power BI Pro is the new October updated version. I wonder we have a compatibility issue here?

**Comment by liprec** [comment]
Just running thru the issue list: is this still an issue?

Most issues just after the release were related to the caching mechanism of either the browser or the Power BI desktop.

**Comment by goldtael** [comment]
Hi Jan:
The issue was gone. I don't know why. I had the problems in the office (not at home) for about a week and then one Monday morning, my computer did some windows updates and all in a sudden everything worked fine. It is still working fine now. Thank you very much for the visual. It is fantastic.

**Comment by SlippingAway** [comment]
Hi @liprec. Thanks for this slicer. I cannot find the way to automatically expand the list. Could you guide me? I'm on Power BI Desktop Version: 2.51.4885.701 64-bit (October 2017).
