### ISSUE TITLE
Slicer doesn't filter data according to native slicer on specific dataset

### ISSUE THREAD

**Issue by ElenaKamaleeva** [liprec/powerbi-hierarchySlicer#121]
When we set data filter only 2014 year, HS still keep date items up to 2013
All details and dataset in attachments

![2020-05-18_2056](https://user-images.githubusercontent.com/48681453/82365612-8d145000-9a19-11ea-8349-8c1c0057da18.png)

[bug.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/4652495/bug.zip)

**Comment by liprec** [comment]
Hi @ElenaKamaleeva,

Looks to me that this is related to the auto-created date hierarchy.

If I use the same slicer in combination with a table you see the same behavior: year 2013 is also available.
![image](https://user-images.githubusercontent.com/12474072/82444396-74507c80-9aa3-11ea-8b0e-76cf789abbbd.png)

Thanks, JP
