### ISSUE TITLE
Slicer selection issue

### ISSUE THREAD

**Issue by ElenaKamaleeva** [liprec/powerbi-hierarchySlicer#122]
1. Slicer doesn't keep selected checkbox. 
Select any item, then switch to focus mode
After returning to report page checkbox is not selected

![hs checkbox clear](https://user-images.githubusercontent.com/48681453/82368105-8687d780-9a1d-11ea-918b-81209adf6c35.gif)

**Comment by liprec** [comment]
Hi @ElenaKamaleeva,

It looks like this is related to the fact that `Name` is a GroupOnKey column and those columns are generating incorrect filters. If I try the same scenario with e.g. `BabyID` the selection is preserved from switching between normal and focus mode.

-JP
