### ISSUE TITLE
Question about data implementation on GroupOnKey 

### ISSUE THREAD

**Issue by ElenaKamaleeva** [liprec/powerbi-hierarchySlicer#123]
Is decomposited data expected?
When re-open report with new 2.1.0 version of HS slicers all data distributes in a different way, not combined by name

![don't_count](https://user-images.githubusercontent.com/48681453/82369002-04001780-9a1f-11ea-998b-f6fc73cd2c85.png)
[GroupOnKey-BabyGrowthData2(Hierarchy Slicer).zip](https://github.com/liprec/powerbi-hierarchySlicer/files/4652664/GroupOnKey-BabyGrowthData2.Hierarchy.Slicer.zip)

**Comment by liprec** [comment]
@ElenaKamaleeva, thanks for the feedback.

After several discussion the conclusion is that the support for GroupOnKey data is almost impossible as the dataview object is missing some key information.
This is specially the case if the GroupOnKey consists of multiple columns, but apparently this is also the case if the key and value column are different. In both cases there is no option to create a correct `tupleFilter` to pass to other visuals.

-JP
