### ISSUE TITLE
[BUG] [UX] Incorrect single selection after ctrl multi-selection 

### ISSUE THREAD

**Issue by liprec** [liprec/powerbi-hierarchySlicer#127]
**Describe the bug**
After a multi selection via the CTRL selection and selecting a already selected item, the selection is cleared.

**To Reproduce**
1. Create hierarchy
2. Multi select items via CTRL
3. Single select an selected item
4. See selection is empty

**Expected behavior**
Only select the single selected item

**Power BI info (please complete the following information):**
 - Online [yes/no]: bith
 - Browser [e.g. chrome, safari]: Edge
 - Desktop version: June 2020

**Comment by JonhSilver** [comment]
Also not work cmd button on apple, cant multi select

**Comment by JonhSilver** [comment]
https://community.powerbi.com/t5/Desktop/Date-hierachy-slicer-problem/m-p/1119057#M512112

https://youtu.be/UBuUb1szRTA

**Comment by liprec** [comment]
Hi @JonhSilver,

The issue you are referencing to is about an issue that the previous version had. With the current version (2.1.1) this issue has been fixed.
Support for the Apple command key I will add in the next release.

-JP

**Comment by JonhSilver** [comment]
Stoped working in Mozilla FireFox

**Comment by JonhSilver** [comment]
How long wait for update? As i see commit is pending but PBI does not updating Slicer

**Comment by liprec** [comment]
Solved with the v2.1.3 release
