### ISSUE TITLE
[BUG] wrong info everywhere and bugs

### ISSUE THREAD

**Issue by JonhSilver** [liprec/powerbi-hierarchySlicer#129]
![image](https://user-images.githubusercontent.com/24619483/87753180-af083400-c80a-11ea-88e2-71337cefcd82.png)
![image](https://user-images.githubusercontent.com/24619483/87753281-f1317580-c80a-11ea-8de5-8a8eba8d0d53.png)

Party show https://streamable.com/cnbri4

All Hierarchy slicer in old projects still broken and do not automatically fixed after update
Need default without ctrl multiselect !!!!
Mac user still cant use ctrl
Not working in Firefox
Items Text Size cant be sized more than 10pt size https://streamable.com/9cjdvp

**Comment by liprec** [comment]
Currently the 2.1.1 version is available in production as the most recent version, see:
![image](https://user-images.githubusercontent.com/12474072/87762548-9a7c6980-c813-11ea-9172-647ffe7f167f.png)

This version is released the beginning of this month, July 2020, and in a couple of weeks a new version (v2.1.3) will be released that fixes the bugs #126 and  #127 and the overlapping items when the font is to big. 

Unfortunately the AppSource listing is updated directly after a new version is approved even if the new version is not yet available in the production tiers.

So please be patience.

-JP
