### ISSUE TITLE
The hierarchy Indicator (little triangle) colour doesn't use Font color 

### ISSUE THREAD

**Issue by robrien6** [liprec/powerbi-hierarchySlicer#13]
Hi,

Please can you have the little triangle that indicates an expandable hierarchy use the color that is used for the Item font color?

We use dark backgrounds for our reports with white text, so the little black triangle is invisible against the dark background.

![invisible triangle](https://user-images.githubusercontent.com/26488930/32332607-d3e519f6-bfdd-11e7-8f35-ffd3ae3ab545.jpg)

**Comment by liprec** [comment]
It should already be the same color as the label text, but somehow it isn't. I filed it as bug and it will be solved in the next release.
Thanks.

**Comment by robrien6** [comment]
Hi, just to follow up , I noticed that once published to the service or to Power BI Report server the visual behaves as expected.  It seems it is only in the desktop client (I was using the October Power BI Report Server client) that the font colour doesnt apply properly.

**Comment by liprec** [comment]
This is fixed in the latest version (v.1.2.x)
