### ISSUE TITLE
Search Mechanism to search all levels of the hierarchy not just the lowest level

### ISSUE THREAD

**Issue by robrien6** [liprec/powerbi-hierarchySlicer#14]
Hi,

this is an enhancement request.  for the Hierarchy slicer, when the search bar is turned on that the search filters based on  all levels of the hierarchy  rather than just the lowest?

Eg if I have the following in a hierarchy 

bob
  |--pete
  |--sue

If I use the search bar to search for 'bob' I get no results back because the search is only applied at the lowest level.

**Comment by liprec** [comment]
This behavior is already available. The only thing is that if you are searching for 'sue' it will become the only visible member in the hierarchy, so 'bob' is not shown. If you select 'sue' and clear the searchterm 'sue; is selected and 'bob' will be back as parent.

**Comment by liprec** [comment]
The search logic is changed with the latest release (v1.2.x) and this should be fixed.
