### ISSUE TITLE
Unexpected Error When Search is Enabled

### ISSUE THREAD

**Issue by drvela** [liprec/powerbi-hierarchySlicer#15]
Getting an Unexpected Error popup in Power BI Desktop, seems to be correlated to search being enabled. Once the error occurs I can't select/deselect anything without the error popping up. Disabling the search bar gets rid of the error. Using October release of Power BI and v1.15.0 of the slicer. Thanks!

[heirarchy_slicer_error.txt](https://github.com/liprec/powerbi-hierarchySlicer/files/1447846/heirarchy_slicer_error.txt)

**Comment by gerbenis** [comment]
I'm getting the same error when search is combined with "Empty Leafs" option. I created hierarchy from Parent-Child relationship in a table using the following [pattern](http://www.daxpatterns.com/parent-child-hierarchies/). This produces some (Blank) entries in the slicer that I can filter by disabling "Empty Leafs" option. However, if enable search, then filtering fails most of the time.

**Comment by liprec** [comment]
Thanks for the feedback. I will look into this case and if I have any other question I will let you know.

**Comment by liprec** [comment]
In the latest version (v.1.2.x) the search logic is changed and I do not experience this issue anymore.
If it still there, please open the issue again.

-JP
