### ISSUE TITLE
Standard slicer checkboxes shifts after hierarchy slicer being installed

### ISSUE THREAD

**Issue by dmitry-ra** [liprec/powerbi-hierarchySlicer#17]
Repro steps:

1. Create new power bi desktop project
2. Add table with some data and show it in a default slicer
3. Install HierarchySlicer

**Expected result:**
HierarchySlicer does not affect to the default visuals.

**Actual result:**
Default slicer checkboxes are jump to the left as shown below.

**Power BI Desktop (RS):** Version: 2.51.4885.1423 64-bit (October 2017)
**HierarchySlicer:** HierarchySlicer.1.1.5.0.pbiviz

![image](https://user-images.githubusercontent.com/1330610/33838696-4a9c2382-dea1-11e7-9891-1fcafebdddcf.png)

**Comment by liprec** [comment]
Thansk for your feedback (and somehow I missed this, my bad). But I will look into this if it is still valid for the current release of Power BI desktop and is so add a fix.

-JP

**Comment by liprec** [comment]
This is fixed in the latest version (v.1.2.x)
