### ISSUE TITLE
White tools option

### ISSUE THREAD

**Issue by DNC1971** [liprec/powerbi-hierarchySlicer#18]
I love this visual but use it on a black background and the tools and drop arrows are not visible. It would be great if you could add an option to turn these to white. Thanks

**Comment by liprec** [comment]
Thanks for the feedback. I will look into this and add this improvement in a next version.

**Comment by liprec** [comment]
In the latest version (v.1.2.x) the drop down arrows have the same color as the item text. And I added an option coloring the searchbox.

**Comment by DNC1971** [comment]
Thank you. Is this version in the MS store now?

**Comment by DNC1971** [comment]
This was working but now seems to have stopped working and the arrows and selection tools are back to being black again.

**Comment by DNC1971** [comment]
This feature is still not working in the latest version. It worked briefly when you first released version 1.2x but it then stopped working when this version was retracted and has since not worked since. It would be great if you can fix this.

**Comment by liprec** [comment]
When I look at my/recent version the little arrows are linked to the `Font color` of the `Items` and I can change them to white with a black background via the default `Background` option.
 Only thing I noticed is that the `Background` of the `Items` is doing nothing, but I doubt that it is still useful.
