### ISSUE TITLE
Ragged hierarchies support

### ISSUE THREAD

**Issue by RadimHampel** [liprec/powerbi-hierarchySlicer#19]
Hi, I'd love to see support for ragged hierarchies. I know that it supports scenario when control hides member when label is empty. I would like to extend this with ability to hide member when label is equal to parent label. 

Example, I'd like not to show members on 3rd and deeper levels.
Region
+Subregion
++Subregion
+++Subregion

Thanks!

**Comment by liprec** [comment]
Thanks for the feedback and I will add this in a next version.

-JP

**Comment by liprec** [comment]
The v2 version is now available and should address this issue.

Thanks, Jan Pieter
