### ISSUE TITLE
Add support to sync slicer

### ISSUE THREAD

**Issue by molotch** [liprec/powerbi-hierarchySlicer#22]
Would be great if you could add support for the new feature to sync and hide slicers over several pages in the report.

**Comment by liprec** [comment]
At this moment it is not possible to use this feature: it is not exposed to the Custom Visual API.
But as soon as it is possible I will add this to the visual.

**Comment by jdelhoyovillar** [comment]
Hi!
Do you know approximately when the syncing feature could be functional in the add in?
Thanks.

**Comment by liprec** [comment]
No ETA yet: API is still not capable

**Comment by MathieuGaloseau** [comment]
Hello,
I'm also looking forward to this feature. Have you any news?
Thanks.

**Comment by schuffa** [comment]
Seems to work meanwhile in service?! Can you please confirm that this is now a lasting feature?

**Comment by liprec** [comment]
Thanks for the update and it looks like it is been enabled for multilevel slicer.
Looks like this feature request can be closed.
