### ISSUE TITLE
cant create pbiviz package

### ISSUE THREAD

**Issue by aj0271** [liprec/powerbi-hierarchySlicer#23]
Missing power bi visual utils.

I originally need it to increase the limit for data reduction algorithm from 4000 to 11000.

**Comment by liprec** [comment]
Please note that the code here on GitHub is not the same as the visual, as the original visual is still using the legacy API and this code is the initial migration code to the new API.
But the migration is not finished and therefor this code is not compiling, or either not generating a working visual.
Please be patience as I need to finish the migration.

And I have an increase of the datapoints scheduled for a future release.

**Comment by Darune** [comment]
Hi, 

Any news on this ? 

Thanks for your work.

**Comment by liprec** [comment]
Still not working.
I am working on a new version of the visual and will update this repository with the current running code. (and probably remove this transformation attempt)

-JP

**Comment by liprec** [comment]
I have updated the repository with the latest code based on the legacy code.
And the max data point is increased with the latest version (v1.2.x) to 30,000.

**Comment by Darune** [comment]
Great thanks !
