### ISSUE TITLE
Add support for persistent filters

### ISSUE THREAD

**Issue by NielsSkytte** [liprec/powerbi-hierarchySlicer#25]
Hi

Support for persistent filters would be great (https://powerbi.microsoft.com/en-us/blog/announcing-persistent-filters-in-the-service/) sounds like it should be possible :-)

**Comment by liprec** [comment]
It sounds indeed possible, but it isn't at this moment.
Power BI doesn't support persistent filters for my HierarchySlicer yet.

Hopefully it will come in the future so I can implement it.

**Comment by liprec** [comment]
I noticed that Power BI now supports persistent filters for my visual, so closing this issue.

-JP
