### ISSUE TITLE
changes not pushed when code modified to pbiviz

### ISSUE THREAD

**Issue by shreyanshmohnot** [liprec/powerbi-hierarchySlicer#26]
I tried to modify the code, but the changes are unable to reflect in power bi visual after updating. Simple as well as complex modification like - changing (blank) to None, setting background color for slicer text.

![capture](https://user-images.githubusercontent.com/9215778/41304457-35b8f92c-6e3e-11e8-9cb9-7d5a6c956344.JPG)

**Comment by liprec** [comment]
If you want to use a different version that the official released version, you need to change the visual ID.
Or else Power BI will use the code of the official version.

Q: what do you mis in the current version regarding background color of the slicer text?

**Comment by shreyanshmohnot** [comment]
Thanks for your response. Well from my requirement specifications I need to highlight the parent labels. Hence I am trying to configure that through your code.
Could you let me know where I can add the **background-color** option?

**Comment by liprec** [comment]
The background is set at line [2293](https://github.com/liprec/powerbi-hierarchySlicer/blob/legacyVersion/resources/HierarchySlicer.js#L2293) of `HierarchySlicer.js`.

But I am interested by the idea to alternate font-/back colors of each level. I will add it to the backlog and will implement it in a future release.

**Comment by shreyanshmohnot** [comment]
Yeah please add them, they would ease a lot. Also if there is some format option to change those colors would be great too. For now, I tried changing visual id - HierarchySlicer1458836712039 to sh773776539317754679831 (some thing like this) in every file, but unable to see the changes in the visual.
Any opinion on this?

**Comment by liprec** [comment]
You should change the ID in the `HierarchySlicer.js`, `HierarchySlicer.css` and the `pbiviz.json` file.
And after that run the build task and the package task.
That should do the trick.
