### ISSUE TITLE
Font family

### ISSUE THREAD

**Issue by mrdavid-williams** [liprec/powerbi-hierarchySlicer#28]
Please add Font family selection for Header and Items.

![image](https://user-images.githubusercontent.com/40292101/41459624-60f93298-708a-11e8-961e-4ce91dfb039c.png)

**Comment by liprec** [comment]
Thanks for the feedback. Although `font family` is not official supported, I going to take a look if it is possible.

**Comment by liprec** [comment]
The v2 version is now available and should fix this issue.

Thanks, Jan Pieter
