### ISSUE TITLE
weird behavior on select all

### ISSUE THREAD

**Issue by shreyanshmohnot** [liprec/powerbi-hierarchySlicer#29]
Today lately hierarchy slicer has been showing unnoticed behavior when I try to use option of Select All in the slicer. 

![screenshot 4](https://user-images.githubusercontent.com/9215778/42230346-c008ac8e-7eb6-11e8-9c5f-04ec85b03563.png)

**Comment by liprec** [comment]
Can you elaborate your issue a little bit more as I do not see any issues with the 'select all' option.

**Comment by shreyanshmohnot** [comment]
Well when I select the "Select All' option, only one selection is made i.e. as in the above image. Also when I try to deselect, it keeps on loading the values. Although I have turned off the single select option as well as empty leaf option.

**Comment by liprec** [comment]
Can you first try to `clear` the current selection and then try if `select all` is working as it should be?
Problem is that I cannot reproduce this behavior.

**Comment by shreyanshmohnot** [comment]
This is happening since I have turned off the **Empty Leaf** feature. If its turned on than, all the selection are done appropriately. Otherwise in my case it selects only one row on **Select All** instead of all the rows as should it happen when **Select All** is checked.

I also tried the previous versions, the problem still persists.

**Comment by liprec** [comment]
Is is possible to share a sample (PBIX) of your report with this behavior?
It will make it a lot easier to determine what is causing the problem.

**Comment by shreyanshmohnot** [comment]
Sorry I cannot share the data with you. But I probably think the data which I am trying to load is producing those errors. Whenever I try to load the same data using excel file the slicer works great. But if I try to load it using database connection it produces different effect. [where on checking select all option - it only checks one single row]. I hope to try to remove it. Thanks for all your help. I highly appreciate your concern in this.

Also please check your email [mail@datascenarios.nl] too

**Comment by shreyanshmohnot** [comment]
Hi.
Could you check the problem with the slicer on empty leaf feature? I have attaches a pbix file for reference,
[file.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/2176881/file.zip)

**Comment by liprec** [comment]
Fixed with version v1.3
