### ISSUE TITLE
Child nodes display under the wrong parent when expanding

### ISSUE THREAD

**Issue by keithelm** [liprec/powerbi-hierarchySlicer#3]
Using visual version 1.0.6.0 (also had used 0.7.9.0 with same issue).

I have a three level hierarchy of Region - Manager - Employee.  Level 1 has three values, level 2 typically has less than 5 managers per region, and level 3 has up to 20 employees per manager.  If I've expanded to the manager level (e.g., Americas\<mgr>) and then attempt to expand to the third level I see employees rendered under the wrong manager.

If I use the See Data functionality, I notice that the underlying data is not sorted by these three levels (some are though).  The employees that render under the wrong manager seem to be those at these unsorted locations.  The employee will render in the hierarchy under the manager from the previous row's data.  

For example, if my data from the Show Data view is as follows:
americas\mgr1\empl1
americas\mgr1\empl2
americas\mgr1\empl3
americas\mgr2\empl4
americas\mgr1\empl5
I see empl5 incorrectly render under mgr2 in the hierarchy view.

**Comment by liprec** [comment]
This is caused because the levels are not correctly sorted. The visual self doesn't sort the levels and is rendering the fields and levels 'just as they are provided by Power BI'.
You can try to add the fields in the same order as the levels in the hierarchy at it should respect the correct sorting.
For a future version I am looking at options for automaticly sorting.

**Comment by keithelm** [comment]
Thanks for taking a look and confirming my suspicion.  AFAIK, I can’t control the “PBI ordering”.  Even if I add an ORDER BY on the original query for the data source, my understanding is that once I add a slicer or other filter on the data that I’m no longer guaranteed any ordering which existed in the original dataset.  So the new feature to sort in the visual itself will help greatly.

-Keith

**Comment by liprec** [comment]
By default Power BI sorts columns either alphabetical or if the type is numeric accordingly. You can control the sorting other with the option 'Sort by column' if you need a different sort order: e.g. sorting of month names. You can take a look at the following article for more explanation: https://powerbi.microsoft.com/en-us/documentation/powerbi-desktop-sort-by-column/

**Comment by keithelm** [comment]
Jan Pieter, I previously looked at the link about specifying an alternate sort column.  I am familiar with that capability and have used it for custom sorting in some other scenarios.  The problem here is that I can’t sort a single way and satisfy all of the slicing.  There is a single dataset (let’s call it work), and I am attempting to use multiple hierarchy slicers on this same dataset.  For example, one slicer is on <region, manager, employee>, a second slicer is on <product, category, subcategory> [for the type of work request], etc.  I might choose to sort on one of those dimensions in the query, but the data for my second slicer won’t render correctly.

Did you abandon the idea of sorting the data in the control?  I looked a bit at the source to see if this might be something I could contribute a fix for, but don’t want to invest there if you already investigated and found it wouldn’t work, hit some technical issue, etc.


-Keith

**Comment by liprec** [comment]
Since version 1.1.x I added the option back to manual influence the sort order via the little menu at the top right corner of the visual. Hope that this can help you in achieving the desired behavior.

Problem with sorting in the visual self is that I only can sort alphabetically as there is no metadata for an correct sorting.
