### ISSUE TITLE
Selection disappears after going back from focus mode

### ISSUE THREAD

**Issue by jstimac** [liprec/powerbi-hierarchySlicer#30]
When selection/filtering is made in normal mode and user goes to focus mode selection is visible. After exiting focus mode selection is not visible, although filter is working/applied.
When new selection is made, existing selection (that is not visible, but working) is ignored as it was not selected. It is the case when single select is both on or off.

**Comment by liprec** [comment]
Thanks and I will look into this for a next release.

**Comment by liprec** [comment]
Fixed with version v1.3
