### ISSUE TITLE
Will this custom visual become certified?

### ISSUE THREAD

**Issue by StevenRouleau** [liprec/powerbi-hierarchySlicer#34]
Hello,

Is there a plan to get this custom visual Certified in the MS AppSource?

The process/requirements for certification are listed here, and is followed by a list of all certified custom visuals.
https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals-certified

Best regards,

Steven

**Comment by liprec** [comment]
Issue is related to the migration to the new API (#32) as certified visuals needs to use the new Power BI Custom Visual API.
As soon as the slicer is migrated to the new API, I will submit it to be certified.

**Comment by kanikajain206** [comment]
Still waiting for the visual to get Microsoft Certified :)
Any expected date ?

**Comment by clausaggeboe** [comment]
Any news on this item?

**Comment by arenphansen** [comment]
Hi @liprec, I know you're working on it, but getting Microsoft certified would be AWESOME! I showed colleagues I work with and was about to publish it before realizing I couldn't in my organization. The tool you've made is a big improvement and would love to free up space on my screens with my many duplicative slicers right now. All your hard work is much appreciated!

**Comment by AntonioMoller** [comment]
Please get it Certified we need this soooooo much

**Comment by koureasstavros** [comment]
Hello, congratulations for this fantastic visual.
We are about to use this visual in our company but unfortunately, we wait this to be Certified.
In your page, you describe that is in the approved stage but don't know when this announcement has been published: https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer-changelog.html?tabs=docs-open
The version you describe is your announcement is 2.0.18 while 2.0.23 is published already in PowerBI in 2017 without beeing Certified ad we are a little bit confused.

**Comment by liprec** [comment]
Hi @s19k15 ,

Thanks for the feedback and I will update the documentation to the current situation and to add some more confusion: currently version 2.0.22 is available for everybody.
But I am trying to get more information about the certification process as I do not know the current status yet.

Thanks, Jan Pieter

**Comment by koureasstavros** [comment]
Hi again, thanks and I appreciate your response!
Basically I can see v2.0.23 in PowerBI and not the v2.0.2.22. Anyway, do you have the date when you submitted the visual for certification?

Στάλθηκε από το iPhone μου

**Comment by Nikkimirri** [comment]
This is really needed, hope you get this certified asap.

**Comment by liprec** [comment]
@All,

The HierarchySlicer is just certified. Docs and AppSource are not yet updated, but Power BI is updated.

Thanks, JP

**Comment by koureasstavros** [comment]
Hi again,

What exactly you mean PowerBI is updated? I am unable to find the certified version in PowerBI or AppSource...


Thanks

**Comment by arenphansen** [comment]
Hi @liprec, was very excited to hear you got it certified but I'm also not seeing where like @s19k15 described? Are there still additional steps you have to do? Thanks!
