### ISSUE TITLE
Can't see last hierarhy member

### ISSUE THREAD

**Issue by ppguu** [liprec/powerbi-hierarchySlicer#35]
Hello. I find issue in ie 11.492.16299.0 for hierarhy slicer ver 1.3.0 in power bi desktop for report server march 2018:
I create hierarhy year-month and i can't select last element of hierarhy: may 2018.
I can't scroll down. But I see horisontal scroll bar...
This issue don't exist in Chrome or Edge.
![pic1](https://user-images.githubusercontent.com/42176287/43777339-2db0009c-9a5b-11e8-9ab3-9ced5ae66354.png)
![pic2](https://user-images.githubusercontent.com/42176287/43777340-2edcb41a-9a5b-11e8-87fc-1ad7bdcabaf6.png)

**Comment by liprec** [comment]
Is this still an issue with the latest release of Report Server?
As I cannot reproduce this issue with powerbi.com and IE (11.229)
