### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by umbee01** [liprec/powerbi-hierarchySlicer#39]
The site says that this add-in, powerbi-hierarchySlicer can send data over the internet. Is this automatic, can it be disabled?

**Comment by liprec** [comment]
The slicer it self is not sending any data over the internet as stated in the privacy statement: https://azurebi-docs.jppp.org/privacy-terms.html.
Can you add the link of where at the site this is stated?

**Comment by umbee01** [comment]
https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380820?tab=Overview at the bottom of the page.

Is this referring to something else?

Thank you.

**Comment by umbee01** [comment]
Hi. I was wondering if you were able to look at the link at this site that stated the add-in send data over the internet?

**Comment by liprec** [comment]
Sorry @umbee01 for my late reaction, but these statements are generic for all Power BI visuals and cannot be changed from my side.
Only thing I can say is that my visual is not sending any data, only consuming data provided by Power BI.

**Comment by umbee01** [comment]
Thank you!
