### ISSUE TITLE
Too Many Values. Not displaying all data.

### ISSUE THREAD

**Issue by mmolaro** [liprec/powerbi-hierarchySlicer#4]
Thanks for the great slicer. 

When I try to use it with a test dataset with 40 entries at the first level in the hierarchy it doesn't work and only shows 10. Trying to search or expand the entries doesn't help get all the data needed into the slicer. 

I get the little circle i info icon informing me that there are too many values and it is not showing all of them. Is it possible to expand how many are shown in the slicer somehow?

**Comment by mmolaro** [comment]
Suggested change I think will fix this:

In [capabilities.json](https://github.com/liprec/powerbi-hierarchySlicer/blob/master/capabilities.json)
`                ], "dataReductionAlgorithm": { "bottom": { "count": 4000 } }
`
increase 4000 to the maximum allowed value of 30000
per 
https://github.com/Microsoft/PowerBI-visuals/blob/master/Capabilities/DataViewMappings.md

**Comment by liprec** [comment]
With the latest update (v1.2.x) the max allowed data point is increased to 30.000
