### ISSUE TITLE
License

### ISSUE THREAD

**Issue by umbee01** [liprec/powerbi-hierarchySlicer#41]
What license applies to the use of powerbi-hierarchySlicer.

I see a this https://az158878.vo.msecnd.net/marketing/Partner_21474846986/Product_42949680652/Asset_9bfe0026-54af-406f-a7bc-27f9389b4165/PowerBIDefaultCustomVisualEULA.pdf

and github says MIT license.

I am not sure of one or the other or both apply

 

Thank you.

**Comment by liprec** [comment]
The main difference is that the link you referring to is the EULA, End User License Agreement, while the code itself is indeed MIT license. So if you are using the visual from AppSource you are accepting the EULA (see link), but if you create/compile the visual yourself via the code, the MIT license applies.
