### ISSUE TITLE
Empty leaves not working

### ISSUE THREAD

**Issue by DNC1971** [liprec/powerbi-hierarchySlicer#42]
One of the key features of this vision that has always been great has been the Empty Leaves function.  This used to work very well but it now seems to have stopped working in my dashboards. Even older version of my files where it previously worked it is now not working. Not sure if the recent version of Power BI has affected this feature. My slicers that used to exclude all the blanks are now showing them so it would be great if you could fix this. Thanks for all the efforts you put into this great visual.

**Comment by liprec** [comment]
Can you share an example pbix file with this behavior with me?
I am not aware that there are any issues at this moment related to the empty leaves functionality.

**Comment by liprec** [comment]
The v2 version is now available and should fix this issue.

Thanks, Jan Pieter
