### ISSUE TITLE
Select Level 1 with multi-Select not working

### ISSUE THREAD

**Issue by devaccount89** [liprec/powerbi-hierarchySlicer#43]
Hi JP, 

when having 5 levels in the hierarchy and multi select enabled:
When you select the complete "Level 1" then the HS applies the filter, but did not mark the whole Element as select and just showing the loading bar. 

Could you please investigate? 
Thanks a lot. 

Best, 

Dev89
![image](https://user-images.githubusercontent.com/25116639/45739503-79389b00-bbf3-11e8-8276-ad9ec6b195bb.png)

![image](https://user-images.githubusercontent.com/25116639/45739541-8d7c9800-bbf3-11e8-9017-294dc26bd19f.png)
This status will remain and not change ( the tick will not show up; however the filter is applied to the data ). It does not appear on lower levels.

**Comment by liprec** [comment]
Is it possible to share an example file with this behavior?

Thanks, JP

**Comment by liprec** [comment]
Closed due to inactivity.
Feel free to open the issue again if it still exist.

-JP
