### ISSUE TITLE
Ragged Hierarchies and the Select All Option

### ISSUE THREAD

**Issue by metamoof** [liprec/powerbi-hierarchySlicer#45]
Hi,

I'm using the [Parent-Child Hierarchies DAX Pattern](https://www.daxpatterns.com/parent-child-hierarchies/) along with this Hierarchy Slicer. My Hierarchy is ragged, going to a depth of three in some cases, and a depth of two in others. 

It works great when I don't have the Select All option enabled, but when I click on Select All, I see weird behaviour, as you are triggering the `ISFILTERED()` function for all depths, even depths that are not possible.

Could you somehow link the Empty Leaves option to the Select All Selector? If empty leaves is disabled, then Select All should not Select the empty leaves. 

For the moment, I've had to disable Select All, which is a bit of cognitive dissonance for my users.

Thanks!

**Comment by liprec** [comment]
The next version will have a new mechanism for determine the 'smallest' filter that fits the selection.
And for `Select All` it will return an empty filter.

**Comment by liprec** [comment]
The v2 version is now available and should fix this issue.

Thanks, Jan Pieter
