### ISSUE TITLE
If select all is bookmarked and data values are added, new select option appear unselected 

### ISSUE THREAD

**Issue by johannes-celix** [liprec/powerbi-hierarchySlicer#46]
If select all is bookmarked and data values are added, new select option appear unselected.

This is a bit unfriendly as we import new data every night and we use this hierachy slicer as date selector.

We kindly ask to make an improvement for this.

Document details
⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
The `Select All` will have a different behavior in the next version. It will clear out the complete selection instead of selecting the current available members.

**Comment by johannes-celix** [comment]
Thank you, for this information. Do you have a rough time estimation when you are going to release this new version including the behaviour?
KR,
Johannes

**Comment by liprec** [comment]
Sorry, but at this moment I do not have an idea when the new version will be available.

**Comment by johannes-celix** [comment]
Ok, but thanks

**Comment by liprec** [comment]
The v2 version is now available and should fix this issue.

Thanks, Jan Pieter
