### ISSUE TITLE
Hierarchie Slicer - LeafMemberIf ChildIsBlank or ChildIsSelf

### ISSUE THREAD

**Issue by MarcusWegener** [liprec/powerbi-hierarchySlicer#47]
Hi,
it would be cool if there was an option to say "LeafMemberIf ChildIsBlank or ChildIsSelf"
As an extension to the option "Empty levels".
Analog SSAS RootMemberIf = ParentIsBlank, ParentIsSelf, ...

best regards
Marcus

**Comment by liprec** [comment]
The v2 version is now available and should address this issue.

Thanks, Jan Pieter
