### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by lehanest95** [liprec/powerbi-hierarchySlicer#5]
While using 1.0.6.0 version of the visual:
When the list to scroll is too long for the box size, the bottom part is cut off. It appears for a moment when you scroll down, but it 'bounces back' when you stop scrolling. Thus, it is not possible to select the bottom items.
Same scrolling issues appear in both Browser and Mobile App(iOS).
As for the Mobile App - it doesn't scroll at all. :-(

**Comment by liprec** [comment]
Good news: I have found what is really causing the scrolling issues.
At this moment I am finishing everything for submission and will submit the new visual in a couple of days for review. And after that the new version will be available.

**Comment by jess82** [comment]
Hello, when is the estimated release date for the fixes of this bug please? We are desperately waiting for it.
Thanks so much

**Comment by liprec** [comment]
Sorry I missed your comment, but the update is released in the next 1-2 weeks.

**Comment by liprec** [comment]
The latest version of the HierarchySlicer (v1.1.5) is now available for everyone.
Can you confirm that it fixes your issue?

**Comment by jess82** [comment]
That's great to hear. I am unable to find the new version on officestore though. Can you please provide the link? Thanks so much. Can't wait to try it out.

**Comment by liprec** [comment]
The visuals will automatically be updated to the latest version, so you do not need a new version from the store. You can check if the behavior with the same report without any updates.

**Comment by jess82** [comment]
I got it. The vertical scrollbar works much better for us now. Thanks so much. 

Are you planning to add the horizontal scrollbar as well? At the moment, when the text is too long, it is cut off and there is no way to see the full text. If horizontal scrollbar is not possible, adding tooltip to display full text would be great please.

Thanks again.

**Comment by liprec** [comment]
Thanks for the update.
