### ISSUE TITLE
[v2-branch] Date formatting is incorrect

### ISSUE THREAD

**Issue by uve** [liprec/powerbi-hierarchySlicer#53]
### Repro Steps:
1. Create 2 visuals with date hierarchy (webpack version and latest version)
2. Compare date formatting

**Actual result:**
Webpack version has incorrect date formatting. Please take a look the attached report:
[Date Slicer.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/2726491/Date.Slicer.zip)

![date format](https://user-images.githubusercontent.com/534586/50681589-b019ac00-103e-11e9-934f-e2da2be7b56b.gif)

**Comment by liprec** [comment]
Waiting for PR Microsoft/powerbi-visuals-utils-formattingutils#41 before closing
