### ISSUE TITLE
HierarchySlicer checkboxes not rendering properly

### ISSUE THREAD

**Issue by ArunMallick** [liprec/powerbi-hierarchySlicer#58]
*Issue here: HierarchySlicer checkboxes not rendering properly*
The Power BI Portal seems to be having a rendering issue for the visual named "HierarchySlicer". The checkbox showed up on top of the text instead on the left side. The Power BI desktop version seems to be working fine.  
Here is the snap from the Power BI Portal. Thank you.
 
![image](https://user-images.githubusercontent.com/46360368/50666999-226d8c00-0f6c-11e9-801b-3555b0f2ca7c.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
There should already be a fix available for this issue. Is it possible to clear the browser cache and try again?

**Comment by liprec** [comment]
There were some problems with the distribution of the latest version, so it took longer before the correct version was being used be everyone. And everybody should now be using the latest version with a fix for this bug.

**Comment by ArunMallick** [comment]
Confirming that this issue is resolved now. Thank you very much for the support and quick turnaround.

Thank you,
Arun
________________________________
