### ISSUE TITLE
Issue with  Hierachy Filter format 

### ISSUE THREAD

**Issue by jprasannakumar** [liprec/powerbi-hierarchySlicer#59]
*Start issue here*
I m using hierarchy Slicer to view the slicer with hierarchy
The format looks good in the  Power BI Desktop ,but when I move the same  (Publish) to Power BI workspace,the format gets weird.. see images below

Power BI deskTop
![image](https://user-images.githubusercontent.com/46383765/50706092-b180af80-1011-11e9-8cc3-bbf77c820110.png)

Power BI workspace

![image](https://user-images.githubusercontent.com/46383765/50706129-d117d800-1011-11e9-904f-bcc7375afa57.png)

---
#### Document details

⚠ Do not edit this section. It is required for docs.jppp.org ➟ GitHub issue linking.

* document_id=487cd175-be13-40df-a80e-aa1c7f531eb1
* document_url=https://azurebi-docs.jppp.org/powerbi-visuals/hierarchy-slicer.html

**Comment by liprec** [comment]
There is a new version released yesterday and it should be available to everyone. Maybe you should clear the browser cache to make sure that you have the latest version.

**Comment by jprasannakumar** [comment]
Not resolved yet. Let us know the ETA for this one

**Comment by manjirit24** [comment]
I see the same issue even when I updated to the newest version. The rendering is still very much problematic on Power BI service.

**Comment by DanUlrich** [comment]
liprec - Is your comment above about new version released (4 days ago), was this reported issue seen, and that release fixed the problem?  Used your slicer heavily and have many unhappy Dashboard users, so trying to avoid extra time lapse if the answer is readily here.

**Comment by liprec** [comment]
The latest version has a fix for the issue with the checkboxes.
Can you please clear your browser cache and try again?

**Comment by DanUlrich** [comment]
Confirmed all our dashboards and reports in PowerBI.com work once browser cache is cleared.
Couple users it was clear, IE, Edge and Chrome and reboot, but most folks it’s clear cache.

**Comment by liprec** [comment]
Thanks for the confirmation and there were some problems with the distribution of the latest version, so it took longer before the correct version was being used be everyone.
