### ISSUE TITLE
Single-selection not working

### ISSUE THREAD

**Issue by Vanveoveo** [liprec/powerbi-hierarchySlicer#6]
Hi,

Somehow the single-selection does not work properly now. Hierarchy slicer still allows multi-selection even when the single-selection is turned on. Could you fix that? Thanks so much! Otherwise, really like this filter!

**Comment by liprec** [comment]
Hi,

There is already a new version coming within a couple of days containing a fix for this single-select issue.

Thanks, Jan Pieter

**Comment by Vanveoveo** [comment]
Thanks for the information, Jan Pieter! Do you have an expected date/time period when this fix will be released? Our report is dependent on this filter so I hope that it can be release soon! Thanks!

**Comment by liprec** [comment]
The latest version of the HierarchySlicer (v1.1.5) is now available for everyone.
Can you confirm that it fixes your issue?

**Comment by Vanveoveo** [comment]
I have tried deleted the slicer, and downloaded it again from the store. But unfortunately the single-selection issue is still not fixed.

**Comment by liprec** [comment]
You can try to clear the cache of either your browser (if using the service) or of the Power BI Desktop, by empty the directory C:\Users\<user>\AppData\Local\Microsoft\Power BI Desktop.
And you don't have to delete the visual and added to your report: it is automatically updated.

**Comment by Vanveoveo** [comment]
That does not help in my case either. Please let me know if there are other method. Thanks!

**Comment by Vanveoveo** [comment]
Actually it works now! Thank you very much!

**Comment by liprec** [comment]
Thanks for the update.
