### ISSUE TITLE
[v2-branch] HierarchySlicer works incorrectly with duplicated strings

### ISSUE THREAD

**Issue by uve** [liprec/powerbi-hierarchySlicer#61]
This looks like a bug – where did the ‘LL’ go?
Sample report: [GroupOnKey-BabyGrowthData2.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/2762859/GroupOnKey-BabyGrowthData2.zip)

![1](https://user-images.githubusercontent.com/534586/51229367-b8eb7580-198e-11e9-8f28-eb73f1aae551.png)

VS

![2](https://user-images.githubusercontent.com/534586/51229371-bee15680-198e-11e9-8bb7-b434b7895507.png)

**Comment by liprec** [comment]
Cannot reproduce this in my current develop version. Please check if it still exists after the submission of the latest version.

**Comment by openStove** [comment]
I experience the same issue, some leafs are displayed under another Parent....
How can I check wich version of hiearchyslicer is in the file ?

**Comment by liprec** [comment]
@openStove this version if not global available yet, so probably you are experiencing a different issue. You can try solving the issue with leaves under different parent by sort the data via the menu at the top right corner of the visual.
Or rebuilding the hierarchy by adding the field of the hierarchy in the correct order parent -> child.

**Comment by openStove** [comment]
You're right, I missed the bug version... I'm using latest published HierarchySlicer1458836712039
When I "expand all" leafs are in the correct position (as they are in the data itself), but if I just expand a specific parent, then a  part of the children appears under a wrong parent...
I can't post a screenshot here, but I could send it to you via another way ?
