### ISSUE TITLE
[v2-branch] "Hide members" property doesn't work for empty strings

### ISSUE THREAD

**Issue by zBritva** [liprec/powerbi-hierarchySlicer#67]
HS doesn't apply option for empty strings.
![image](https://user-images.githubusercontent.com/10897951/52948963-098a3000-338c-11e9-9d79-a3060998e603.png)

But HS applies option for string data types, if they are null (not empty).
![image](https://user-images.githubusercontent.com/10897951/52948967-0f801100-338c-11e9-9c3d-50d91d9e6e15.png)

**Comment by liprec** [comment]
At this moment I cannot reproduce this. Can you share the pbix?

**Comment by liprec** [comment]
Now by default an empty string ('') is treated the same as an 'null' string, but added an extra option to disable this behavior if needed.
