### ISSUE TITLE
Hierarchy Slices shows weird stuff 

### ISSUE THREAD

**Issue by schiozer** [liprec/powerbi-hierarchySlicer#7]
Hello,

The component is showing weird stuff, like a big plus signal and some bars. This happens on Power Bi Desktop and online. After cleaning browser cache the online versions is fine but Power BI Desktop I am not able to clean that. Could you help me ?

I also have opened a request 
http://community.powerbi.com/t5/Desktop/Hierarchy-Slices-shows-weird-stuff/m-p/275561#M122927

**Comment by liprec** [comment]
First: the issue is identified and a fix is submitted to the store and I am waiting for the approval.
Other thing is: good to hear that clearing the cache is working for the browser version. Can you try deleting the cache from Power BI desktop and look if it is resolved also?
You can clear the cache by empty the directory `C:\Users\<user>\AppData\Local\Microsoft\Power BI Desktop`

Thanks, Jan Pieter

**Comment by schiozer** [comment]
Great, I will check it. Today is holiday here but tomorrow as soon as I get into the office I will test it
I would appreciate if you let me know when the fix will be released
Thanks,
    Em quarta-feira, 11 de outubro de 2017 21:44:40 BRT, Jan Pieter Posthuma <notifications@github.com> escreveu:  
 
 
First: the issue is identified and a fix is submitted to the store and I am waiting for the approval.
Other thing is: good to hear that clearing the cache is working for the browser version. Can you try deleting the cache from Power BI desktop and look if it is resolved also?
You can clear the cache by empty the directory C:\Users\<user>\AppData\Local\Microsoft\Power BI Desktop

Thanks, Jan Pieter

**Comment by schiozer** [comment]
Hi Jan Pieter,
I Just tested deleting the folder you pointer out and ir seems it worked.
Thanks for the support and looking forward tô hear about the release fix. 
Thanks 
Fabio 

Enviado do Yahoo Mail no Android 
 
  Em Qui, 12 12e out 12e 2017 às 17:26, Fabio Schiozer&It;schiozer@yahoo.com.br> escreveu:    Great, I will check it. Today is holiday here but tomorrow as soon as I get into the office I will test it
I would appreciate if you let me know when the fix will be released
Thanks,
    Em quarta-feira, 11 de outubro de 2017 21:44:40 BRT, Jan Pieter Posthuma <notifications@github.com> escreveu:  
 
 
First: the issue is identified and a fix is submitted to the store and I am waiting for the approval.
Other thing is: good to hear that clearing the cache is working for the browser version. Can you try deleting the cache from Power BI desktop and look if it is resolved also?
You can clear the cache by empty the directory C:\Users\<user>\AppData\Local\Microsoft\Power BI Desktop

Thanks, Jan Pieter

**Comment by liprec** [comment]
The latest version of the HierarchySlicer (v1.1.5) is now available for everyone.
Can you confirm that it fixes your issue?
