### ISSUE TITLE
Null value selection does not change Hierarchy Slicer state

### ISSUE THREAD

**Issue by ElenaKamaleeva** [liprec/powerbi-hierarchySlicer#74]
Previous version has expected behavior when selected null value - > displays nothing
2.0.13 version does not change state of the slicer and shows all included data fields
[Hierarchy Slicer null value.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/3062747/Hierarchy.Slicer.null.value.zip)

**Comment by liprec** [comment]
Problem is that the `jsonFilter` object is empty when selecting the `null` row in the table.

**Comment by zBritva** [comment]
Hello @liprec ,

There is some details of bug, actually there is JS exception in the visual:

![HS_NullSelection](https://user-images.githubusercontent.com/10897951/55878917-1ebe5680-5ba6-11e9-8741-19ce6739b678.gif)

It's inside `styleSlicerInputs` method on rendering selection:
![image](https://user-images.githubusercontent.com/10897951/55879007-4ad9d780-5ba6-11e9-88b1-7b799742d3df.png)

Bug is critical, we can't ignore it.

**Comment by liprec** [comment]
Sorry, at this moment I cannot see the error. What browser and environment are you using?

**Comment by zBritva** [comment]
@liprec  It's in chrome 73.0.3683.86

**Comment by liprec** [comment]
@zBritva can you share the PBIX file? Looks like it is happening with certain combintation of formatting settings

**Comment by zBritva** [comment]
I shared in e-mail

**Comment by liprec** [comment]
Sorry missed the attachment, but fix is on its way.
