### ISSUE TITLE
Expand all - collapse all - clear button stopped working this week. 

### ISSUE THREAD

**Issue by JeremyBurnett** [liprec/powerbi-hierarchySlicer#8]
Love this visual! It's worked really well for months... until sometime this past week. It worked last Friday; but not today, in either BI online or the desktop app. It doesn't even work in your sample at https://azurebi.jppp.org/visualizations/. 
Please help! Really love using this tool and don't want to have to redo a bunch of dashboards.

**Comment by liprec** [comment]
There is a fix coming for this issue in the coming days.
And it will auto update the current ones, so you do not have to redo anything.

Thanks, JP

**Comment by liprec** [comment]
The latest version of the HierarchySlicer (v1.1.5) is now available for everyone.
Can you confirm that it fixes your issue?
