### ISSUE TITLE
Visual not working with renamed fields

### ISSUE THREAD

**Issue by jhomiak** [liprec/powerbi-hierarchySlicer#80]
I have version 2.0.15. When I rename the fields located in the "Fields" section, any filters applied to children don't work. The child item will briefly become checked, then the checkmark will disappear, and nothing gets filtered. This is immediately resolved if the renamed fields are reverted to their default names.

This has caused many of my reports to break as I give my fields non-user friendly names, and rename them on the visual.

Repro:
1. Add the Hierarchy Slicer to a page
2. Add 2 or more fields to the fields section
3. Rename the fields to something else
4. Attempt to filter using the hierarchy slicer, and notice that no data is affected.

Thanks,
Jon

**Comment by liprec** [comment]
The v2 version is now available and should fix this issue.

Thanks, Jan Pieter
