### ISSUE TITLE
Issue with hierarchy selection

### ISSUE THREAD

**Issue by Azounet** [liprec/powerbi-hierarchySlicer#89]
Hello,

I have an issue when I try to get all selected values in the slicer using "ALLSELECTED" in dax.

If I select leaves, it works fine, if I select a group, leaves are visually selected but the calculation is not working.

![Issue](http://mr.azo.free.fr/Image1.png)

Here is my formula:
`Entity_bis_val = CALCULATE(SUM(Database[Amount]);ALL(d_entity);d_entity[entity_code] in ALLSELECTED(d_entity_bis[entity_code]))`

Is there another way to get data from all leaves using DAX (I need DAX as I need to disconnect the technical entity from my model).

In order to bring more clarity, [here is the PBIX](https://www.dropbox.com/s/oyxzue2r5cze0g1/T_Selection.pbix?dl=0)

Best Regards
Emilien

**Comment by liprec** [comment]
Probably the best is to wait how your measure is behaving with the upcoming v2 version, which is due next week.
