### ISSUE TITLE
Single select no longer working

### ISSUE THREAD

**Issue by esme** [liprec/powerbi-hierarchySlicer#9]
Hi, the hierachy slicer is great but single select and clear all doesnt work anymore. Any idea on how to fix this?

**Comment by liprec** [comment]
There is a fix coming for this issue in the upcoming days.
And the current versions will automatically be updated when this version is available.

**Comment by liprec** [comment]
The latest version of the HierarchySlicer (v1.1.5) is now available for everyone.
Can you confirm that it fixes your issue?

**Comment by atomek1000** [comment]
Hi, I still have issues with newest version. Unexpected error happens when de-selecting single value

**Comment by liprec** [comment]
Just running thru the issue list: is this still an issue?
Most issues just after the release were related to the caching mechanism of either the browser or the Power BI desktop.
