### ISSUE TITLE
[BUG] The slicer doesnt work on the new version of PowerBI

### ISSUE THREAD

**Issue by pramodx** [liprec/powerbi-hierarchySlicer#91]
**Describe the bug**
I downloaded the visual from AppSource and tried importing it a a custom visual. It says 'Visual successfully imported', but the icon doesn't show up in the Visualisation pane. All other custom visualisation from other sources work for me.

The visual works fine on the PowerBI server

**To Reproduce**

PowerBI version = Version: 2.70.5494.761 64-bit (June 2019)

**Expected behavior**
Visual icon 
![01](https://user-images.githubusercontent.com/2028580/60632688-6d4c5b80-9e4a-11e9-9598-e0bc857e8487.PNG)
![02](https://user-images.githubusercontent.com/2028580/60632691-6d4c5b80-9e4a-11e9-9635-91a836402768.png)
![03](https://user-images.githubusercontent.com/2028580/60632693-6de4f200-9e4a-11e9-807f-10ed1f9f90bb.PNG)

should appear in the Visualisation pane

**Screenshots**

**Power BI info (please complete the following information):**
 - Online [no]: 
 - Browser [e.g. chrome, safari]:
 - Desktop version:  Version: 2.70.5494.761 64-bit (June 2019)

**Additional context**
And if possible please share a PBIX file.

**Comment by liprec** [comment]
Does this issue also exists if you try the v1.3 version of the visual?
The v2 version is not released official yet.

**Comment by liprec** [comment]
As a new version is released last month the issue should not happen again. It this is still an issue, please let me know by either raising a new issue or open this one.

Thanks, Jan Pieter
