### ISSUE TITLE
[BUG] Hierarchy Slicer visual is not showing up with content in screenshot of e-mail subscriptions

### ISSUE THREAD

**Issue by schuffa** [liprec/powerbi-hierarchySlicer#92]
**Describe the bug**
When using the hierarchy slicer in a PBI Report and adding an e-mail subscribing to this report page, the hierarchy slicer visual is NOT shown with content in the screenshot send with the e-mail, but instead only a shield symbol is shown.

**To Reproduce**
Subscribe to report page with hierarchy slicer, send e-mail, check screenshot in e-mail

**Expected behavior**
I would have expected, that the hierarchy slicer visual would show up with content in the screenshot.

**Screenshots**
see example attached
![hierarchy slicer e-mail screenshot bug](https://user-images.githubusercontent.com/51359966/60955147-8ba9cf80-a300-11e9-9145-8c6f8d370b03.jpg)

**Power BI info (please complete the following information):**
 - Online [yes/no]: yes
 - Browser [e.g. chrome, safari]: Chrome
 - Desktop version: Jun, 2019

It might be related to a missing certification of this custom visual? When is the v2 release of this custom visual planned?

**Comment by liprec** [comment]
Closing as it is related to #34.

Thanks, Jan Pieter
