### ISSUE TITLE
TS5023: Unknown compiler option 'strictBindCallApply'.

### ISSUE THREAD

**Issue by stefan-ma22** [liprec/powerbi-hierarchySlicer#94]
Hi When I download the package and run pbiviz start I get the error 

```
ERROR in D:\Projects\PowerBI\CustomVisuals\HierarchySlicer\tsconfig.json
[tsl] ERROR
      TS5023: Unknown compiler option 'strictBindCallApply'.
 @ multi ./.tmp/precompile/visualPlugin.ts visual.js[0]

ERROR in ./.tmp/precompile/visualPlugin.ts
Module build failed (from D:/Users/A22478328/AppData/Roaming/npm/node_modules/powerbi-visuals-tools/node_modules/ts-loader/index.js):
Error: error while parsing tsconfig.json
    at Object.loader (D:\Users\A22478328\AppData\Roaming\npm\node_modules\powerbi-visuals-tools\node_modules\ts-loader\dist\index.js:19:18)
 @ multi ./.tmp/precompile/visualPlugin.ts visual.js[0]
i ｢wdm｣: Failed to compile.
```

This is a version of typescript I am using Version 3.5.3 - basically the version you have in package.json

**Comment by liprec** [comment]
Is it possible that during compiling a different TypeScript compiler is used as `strictBindCallApply` is introduced in version 3.2?
Maybe a global TypeScript version? `npm list -g --depth=0` doesn't show a different version?

**Comment by stefan-ma22** [comment]
Thanks, I found out that I really was using old version of typescript which was in installed globally.
I had to remove it, change package.json to newer one and it runs.

Any chance to help me with another problem ?

```
ERROR in D:\Projects\PowerBI\CustomVisuals\HierarchySlicer\.tmp\precompile\visualPlugin.ts
./.tmp/precompile/visualPlugin.ts
[tsl] ERROR in D:\Projects\PowerBI\CustomVisuals\HierarchySlicer\.tmp\precompile\visualPlugin.ts(3,22)
      TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

ERROR in D:\Projects\PowerBI\CustomVisuals\HierarchySlicer\.tmp\precompile\visualPlugin.ts
./.tmp/precompile/visualPlugin.ts
[tsl] ERROR in D:\Projects\PowerBI\CustomVisuals\HierarchySlicer\.tmp\precompile\visualPlugin.ts(11,14)
      TS7006: Parameter 'options' implicitly has an 'any' type.
```

**Comment by liprec** [comment]
Please update to the latest version of the powerbi-visuals-tools, which contain fixes for this issue.

**Comment by HardRock4Life** [comment]
Installed powerbi-visuals-tools both inside the visual itself, and installed it with `-g` option, too. Still I get the same error...

Do there errors from screenshot affect too?
![image](https://user-images.githubusercontent.com/21273349/72010338-7b57ba80-3279-11ea-80f2-0409cdd99d7e.png)

**Comment by liprec** [comment]
Sorry about this, I have noticed that indeed there is still a small issue with the tooling that is causing this.
And as far as I know: the screenshot is not related to this.

**Comment by iamebadi** [comment]
Hi dear  liprec
I  download  latest version  and after  run  pbiviz start i get the error "TS5023: Unknown compiler option 'strictBindCallApply'."

I do all solution in  this  issue but error remain  and not solved.

I run command  "npm list -g --depth=0"  and below is  result.

C:\Users\myuser\.npm-global
+-- @typescript-eslint/eslint-plugin@2.12.0
+-- @typescript-eslint/parser@2.0.0
+-- eslint@6.8.0
+-- missing-packages@1.9.0
+-- powerbi-visuals-tools@3.1.9
+-- ts-node@8.6.1
+-- types@0.1.1
+-- typescript@3.7.4
+-- typings@2.1.1
`-- weex-toolkit@2.0.0-beta.31

please  help  me.
thanks
