### ISSUE TITLE
Cannot Load Slicer in Power BI service

### ISSUE THREAD

**Issue by ppserzo** [liprec/powerbi-hierarchySlicer#95]
I downloaded ver 2.0.19 of the Hierarchy Slicer.  When I try and upload it into the Organizational Visuals I get an error message "This visual is not supported".  I have everything turned off (meaning, I can upload non-certified visuals) so it should be able to upload.  Please let me know.

**Comment by liprec** [comment]
Did you download it from AppSource (https://appsource.microsoft.com/en-us/product/power-bi-visuals/WA104380820)? That should already be v2.0.
If not: I will update the (pre-)release here at GitHub.
