### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by iamebadi** [liprec/powerbi-hierarchySlicer#97]
Error when compile project with "pbiviz start".

Hi dear Liprec,

I download latest hierarchySlicer from your git but when to compile your project with "pbiviz start" command two error has occurred.

I run the command with administrator privileges.

Screenshot :

[http://s3.picofile.com/file/8370400326/error.jpg]

I want to customize that Custom Visual for RTL direction and add my font-family.

please help.

Thanks.

**Comment by liprec** [comment]
Hi @iamebadi ,

Somehow I cannot see the screenshot, what error do you see exactly?

Thanks, JP

**Comment by iamebadi** [comment]
Screenshot:
here:  
http://s3.picofile.com/file/8370400326/error.jpg
and here:  
https://i.imgur.com/q48o6Oo.jpg
and here:  https://photos.google.com/photo/AF1QipPYMJxCTRgyXtppGhGOLxXWkdGqyykb0HZpxx4Y

Error detail:
 ERROR  Failed to compile with 2 errors                                                                    

 error  in E:\Jobs\Web\setad\Power BI\visuals\powerbi-hierarchySlicer-master-new\.tmp\precompile\visualPlugin.ts

[tsl] ERROR in E:\Jobs\Web\setad\Power BI\visuals\powerbi-hierarchySlicer-master-new\.tmp\precompile\visualPlugin.ts(3,22)
      **TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.**

 error  in E:\Jobs\Web\setad\Power BI\visuals\powerbi-hierarchySlicer-master-new\.tmp\precompile\visualPlugin.ts

[tsl] ERROR in E:\Jobs\Web\setad\Power BI\visuals\powerbi-hierarchySlicer-master-new\.tmp\precompile\visualPlugin.ts(11,14)
      **TS7006: Parameter 'options' implicitly has an 'any' type.**

Thanks again...

**Comment by iamebadi** [comment]
https://github.com/liprec/powerbi-hierarchySlicer/issues/97
    On Monday, August 26, 2019, 12:36:12 PM GMT+4:30, Jan Pieter Posthuma <notifications@github.com> wrote:  
 
 
Hi @iamebadi ,

Somehow I cannot see the screenshot, what error do you see exactly?

Thanks, JP

**Comment by liprec** [comment]
Thanks. Somehow I cannot load the 'picofile' image.
But the easiest way to solve this is to set the `noImplicitAny` to `false` in the `tsconfig.json` file.

There is some things that prevents the `pbiviz start` to work correctly with this setting set to `true`

-JP

**Comment by liprec** [comment]
Closed as related to #94 and fix is coming.

Thanks, Jan Pieter
