### ISSUE TITLE
Settings variable names

### ISSUE THREAD

**Issue by JoshMayberry** [liprec/powerbi-hierarchySlicer#98]
I am trying to set up a custom theme, and would like to setup the style for the HiarchySliders I am using.

The variable names do not match the text that is displayed in teh formatting box, and this is making things difficult.

For example, "Select Color" shows on the formatting screen, but the variable name for it is "select**ed**Color".
Other names such as "hoverColor" match what the formatting screen shows.

**Can you make the formatting screen text match what the camel cased variable names are**?

**Comment by liprec** [comment]
Hi @JoshMayberry,

The main reason why there are some discrepancies in the naming of the attributes is due to the history of those attributes. I can change these attributes, but then all users that have changed those properties, will loose their formatting causing a lot of different issues.

-JP

**Comment by JoshMayberry** [comment]
I meant to change the labeling, not the variable names.
