### ISSUE TITLE
[BUG]Search option does not work

### ISSUE THREAD

**Issue by ElenaKamaleeva** [liprec/powerbi-hierarchySlicer#99]
Open report with HS version 2.0.20
Add search option and set searching item
Actual result: HS doesn't filter by search option
[HierarchySlicer.zip](https://github.com/liprec/powerbi-hierarchySlicer/files/3551945/HierarchySlicer.zip)

**Comment by liprec** [comment]
Hi @ElenaKamaleeva,

Search will start working when the search string is longer as 3 characters.
Can you try if the search is working with more search characters?

Thanks, JP

**Comment by Pmarouga** [comment]
If you want to search less than 3 characters what must you do?
